// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "chatServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::server;

class chatServerHandler : virtual public chatServerIf {
 public:
  chatServerHandler() {
    // Your initialization goes here
  }

  bool findUser(const std::string& username) {
    // Your implementation goes here
    printf("findUser\n");
  }

  bool addUser(const std::string& username) {
    // Your implementation goes here
    printf("addUser\n");
  }

  bool createRoom(const std::string& roomname) {
    // Your implementation goes here
    printf("createRoom\n");
  }

  bool joinRoom(const std::string& roomname) {
    // Your implementation goes here
    printf("joinRoom\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<chatServerHandler> handler(new chatServerHandler());
  ::std::shared_ptr<TProcessor> processor(new chatServerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

